# A Travis CI configuration file.

sudo: required

language: go

go:
  - 1.7

install:
  - go get -u github.com/golang/lint/golint

script:
  - make lint
  - make build

after_script:
  - make clean

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd $TRAVIS_BUILD_DIR;
    git config --global user.email "builds@travis-ci.com";
    git config --global user.name "Travis CI";
    export GIT_TAG="latest";
    git tag -d $GIT_TAG;
    git push --delete origin $GIT_TAG;
    git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
    git push origin $GIT_TAG;
    fi

before_deploy:
  - go get github.com/inconshreveable/mousetrap
  - go get github.com/mattn/go-isatty
  - export build_file_name=wsk
  - export zip_file_name=OpenWhisk_CLI
  - chmod +x tools/travis/build_tag_releases.sh
  - ./tools/travis/build_tag_releases.sh $build_file_name $zip_file_name
  - export RELEASE_PKG_FILE=$(ls $zip_file_name-*.zip)
  - echo "Deploying $RELEASE_PKG_FILE to GitHub releases."

deploy:
  provider: releases
  api_key:
    secure: Yh1aYiM/qIWkPMSVjGUq1g9TjpACjavQ00QAqp4oqghNZc6xBcmdzsfD2VjzVPHleNI1FIZyjJ1x6laRfWBzRkAcJcjUHXA2bO/V0jqePVmgVm75WwTZ/9EaWIJeAg5CQMm5DGS28Yhc60C0ut3ZzKMWGTiKb73UADXPTGd/tjndxjfksX/THXPuInKB9QZesmluBAC2am/x/6J311WA2wqe0p1+9JFwMr8XwIcwzCwgi/d9CFpS1RnVpLE/ORSgmN/dFbZ7A/qVbx377QoxKiEB0jmUwi13f7REFAw18JdgzbQCH3X4HNu9pCJwHEAq3lP2CfmHbAXcViBeji/Xh9PPJVV9TYqO+uT8oPxCPJND1A/3O2xJ8LyZ/FP2bWqG/Ds/8SZCvxfOR/X77opUeZ4qAp7HJMVCsFi3TsnmzxCe0BOxCppVJLhoSZ2rOAPJi9mKgS/Z/VA5VhNNmnPtkReEWK4vT9h3/iCwv9anvC0RKeLckSHpCm5C5otNXtV4L990fL5L5krMatxynHnCmmhYeLg/Ns+5ncax58Y8hmhnhzTqbPGHpe79bJRfvwRI9lboq7kEj4x5O/M16TKRfQ8ZU5UHvrCPdlTfT7NUXRGZkvWX20X6Ta/DRROTF+xZGiq7da3Oi+xyNDx/LmymfR49thjzgIPXVZolknGYQ9Q=
  file_glob: true
  file: ${zip_file_name}-*.zip
  skip_cleanup: true
  on:
    repo: openwhisk/openwhisk-cli
    tags: true
