---
# Tasks for handling CLI customization and publishing

- name: "ensure nginx directory for cli exists"
  file:
    path: "{{ cli.nginxdir  }}"
    state: directory

- set_fact:
    cli_installation_mode="{{ openwhisk_cli.installation_mode }}"

- include: docker_login.yml

- name: "download the binaries from the release page of OpenWhisk CLI"
  include: download_openwhisk_cli.yml
  with_nested:
    - "{{ cli_os }}"
    - "{{ cli_arc }}"
  when: cli_installation_mode == "remote"

- name: "generate content.json for Nginx CLI directory"
  local_action: shell "./createContentJson.sh" "{{ cli.nginxdir }}" "{{ openwhisk_cli_tag }}" "{{ cli_os | join(" ") }}" "{{ openwhisk_cli.dest_name }}" chdir="{{ openwhisk_home }}/ansible/roles/cli/files"
  when: cli_installation_mode == "remote"

- name: "copy the binaries from a local directory to Nginx"
  copy: src={{ openwhisk_cli.location }}/ dest={{ cli.nginxdir }}/
  when: cli_installation_mode == "local"

- include: download_cli.yml
