---
# Tasks for handling CLI customization and publishing

- name: "ensure nginx directory for cli exists"
  file:
    path: "{{ cli.nginxdir  }}"
    state: directory

- set_fact:
    cli_installation_mode="{{ openwhisk_cli.installation_mode }}"

- include: docker_login.yml

- name: "download the binaries for the remote mode"
  include: cli_remote_mode.yml
  when: cli_installation_mode == "remote"

- name: "copy the binaries from a local directory to Nginx directory"
  copy: src={{ openwhisk_cli.location }}/ dest={{ cli.nginxdir }}/
  when: cli_installation_mode == "local"

- include: download_cli.yml
