---
# Delete and recreate the actionsDB for whisk.

- name: delete the {{ db.whisk.actions }} with {{ db_provider }}
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ db.whisk.actions }}"
    method: DELETE
    status_code: 200,404
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes

- name: create {{ db.whisk.actions }} with {{ db_provider }}
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ db.whisk.actions }}"
    method: PUT
    status_code: 200,201
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
