---
# Recreates the views in actionsDB.

- name: get rev of existing whisks-Design document in {{ db.whisk.actions }} with {{ db_provider }}, if it exists
  vars:
    auth_index: "{{ lookup('file', '{{ openwhisk_home }}/ansible/files/whisks_design_document_for_actions_db.json') }}"
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ db.whisk.actions }}/_design/whisks"
    method: HEAD
    status_code: 200,404
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
  register: response

- set_fact:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ db.whisk.actions }}/_design/whisks?rev={{ response.etag | replace('\"', '') }}"
  when: response.status == 200

- set_fact:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ db.whisk.actions }}/_design/whisks"
  when: response.status != 200

- name: create whisks-Design document in {{ db.whisk.actions }} with {{ db_provider }}
  vars:
    auth_index: "{{ lookup('file', '{{ openwhisk_home }}/ansible/files/whisks_design_document_for_actions_db.json') }}"
  uri:
    url: "{{ url }}"
    method: PUT
    status_code: 200,201
    body_format: json
    body: "{{ auth_index }}"
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
