- name: OpenWhisk Controller
  hosts: edge
  tasks:
  - name: (Re)start container
    docker:
      name: controller
      image: whisk/controller
      state: reloaded
      restart_policy: "{{docker.restart.policy}}"
      env:
        "COMPONENT_NAME": "controller"
        "CONSULSERVER_HOST": "{{consul.host}}"
        "CONSUL_HOST_PORT4": "{{consul.port4}}"
        "PORT": 8080
        "WHISK_VERSION_NAME": "{{whisk.version.name}}"
        "WHISK_VERSION_DATE": "{{whisk.version.date}}"
      volumes:
        - "{{whisk.logs.dir}}/controller:/logs"
      ports:
        - "{{controller.port}}:8080"