- name: OpenWhisk Controller
  hosts: edge
  tasks:
  - name: Pull image
    shell: "docker pull {{docker.registry}}whisk/controller:{{docker_image_tag}}"
    when: docker.registry != ""
  - name: (Re)start container
    docker:
      name: controller
      image: "{{docker.registry}}whisk/controller:{{docker_image_tag}}"
      state: reloaded
      restart_policy: "{{docker.restart.policy}}"
      env:
        "COMPONENT_NAME": "controller"
        "CONSULSERVER_HOST": "{{consul.host}}"
        "CONSUL_HOST_PORT4": "{{consul.port4}}"
        "PORT": 8080
        "WHISK_VERSION_NAME": "{{whisk.version.name}}"
        "WHISK_VERSION_DATE": "{{whisk.version.date}}"
      volumes:
        - "{{whisk.logs.dir}}/controller:/logs"
      ports:
        - "{{controller.port}}:8080"
  - name: Wait until Controller is up and running
    wait_for: delay=2 host={{ansible_host}} port={{controller.port}} timeout=60
